server:
  port: 8080

iamslash.name: davidsun

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
      hibernate:
          SQL: debug

spring.h2.console.enabled: true
spring.h2.console.path: '/h2'
spring.h2.console.settings.trace: false
#spring.h2.console.settings.web-allow-others: false

spring.datasource.url: 'jdbc:h2:file:~/test'
spring.datasource.driverClassName: 'org.h2.Driver'
spring.datasource.username: 'sa'
#spring.datasource.password:
spring.jpa.database-platform: 'org.hibernate.dialect.H2Dialect'
spring.jpa.show_sql: true
spring.jpa.properties.hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
spring.jpa.hibernate.ddl-auto: create             # 서버 시작에 테이블 생성
