spring:
  profiles:
    active: local-h2
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  profiles: local-h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: iamslash
      password: 1
      driver-class-name: org.h2.Driver
---
spring:
  profiles: local-mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: iamslash
      password: 1
      driver-class-name: com.mysql.jdbc.Driver